# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Shiny\SecuritiesBundle\Entity\User: bcrypt

    role_hierarchy: #?_switch_user=_exit
            ROLE_ADMIN:       [ROLE_CONTRIBUTEUR, ROLE_MODERATEUR]
            ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        users_provider:
            entity:
                class: SecuritiesBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            provider: users_provider
            guard:
                authenticators:
                    - security.login_form_authenticator

            logout:
                path: /logout
            switch_user: ~

    access_control:
        - { path: ^/admin/test, roles: ROLE_ADMIN }