<?php

namespace Shiny\SecuritiesBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastRegisters($limite)
    {
        $query = $this->createQueryBuilder('u')
            ->orderBy('u.id', 'DESC')
            ->setMaxResults($limite)
            ->getQuery();

        return $query->getResult();
    }

    public function findAllWithPaginate($currentPage, $limite)
    {
        $query = $this->createQueryBuilder('u')
            ->setFirstResult(($currentPage -1) * $limite)
            ->setMaxResults($limite);
        return new Paginator($query, true);
    }

}
