app_homepage:
    path:     /
    defaults: { _controller: AppBundle:App:index }

app_single:
    path:     /{id}
    defaults: { _controller: AppBundle:App:single }
    requirements:
        id: \d+

app_list:
    path:     /list/{page}
    defaults: { _controller: AppBundle:App:list, page: 1 }
    requirements:
        page: \d+

app_handle_search:
    path:     /search/{page}
    defaults: { _controller: AppBundle:App:handleSearch, page: 1 }
    requirements:
        page: \d+

app_contact:
    path:     /contact
    defaults: { _controller: AppBundle:App:contact }