app_homepage:
    path:     /
    defaults: { _controller: AppBundle:App:index }

app_single:
    path:     /{id}
    defaults: { _controller: AppBundle:App:single }
    requirements:
        id: \d+

app_catalogue:
    path:     /catalogue/{page}
    defaults: { _controller: AppBundle:App:catalogue, page: 1 }
    requirements:
        page: \d+

app_list:
    path:     /list/{param}/{id}/{page}
    defaults: { _controller: AppBundle:App:list, page: 1 }
    requirements:
        id: \d+
        page: \d+

app_handle_search:
    path:     /search/{page}
    defaults: { _controller: AppBundle:App:handleSearch, page: 1 }
    requirements:
        page: \d+

app_contact:
    path:     /contact
    defaults: { _controller: AppBundle:App:contact }

app_legale:
    path:     /mentions-legales
    defaults: { _controller: AppBundle:App:legale }