services:
    admin.form.book:
        class: Shiny\AdminBundle\Form\BookType
        arguments: [ "@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    admin.form.prof_add:
        class: Shiny\AdminBundle\Form\ProfAddType
        arguments: [ "@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
