<?php

namespace Shiny\AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWithPaginate($currentPage, $limite)
    {
        $query = $this->createQueryBuilder('c')
            ->orderBy('c.name', 'DESC')
            ->setFirstResult(($currentPage -1) * $limite)
            ->setMaxResults($limite);
        return new Paginator($query);
    }

}
