<?php

namespace Shiny\AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ProfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchFromName($firstName, $lastName)
    {
        $query = $this->createQueryBuilder('p')
            ->where('p.firstName :firstname')
            ->setParameter('firstname', $firstName)
            ->andWhere('p.lastName :lastname')
            ->setParameter('lastname', $lastName)
            ->getQuery();


        return $query->getFirstResult();
    }

    public function getLastProfs($limite)
    {
        $query = $this->createQueryBuilder('p')
            ->orderBy('p.id', 'DESC')
            ->setMaxResults($limite)
            ->getQuery();

        return $query->getResult();
    }

    public function findAllWithPaginate($currentPage, $limite)
    {
        $query = $this->createQueryBuilder('p')
        ->orderBy('p.firstName', 'DESC')
        ->setFirstResult(($currentPage -1) * $limite)
        ->setMaxResults($limite);
        return new Paginator($query, true);
    }
}
