<?php

namespace Shiny\AppBundle\Repository;

/**
 * ProfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchFromName($firstName, $lastName)
    {
        $query = $this->createQueryBuilder('p')
            ->where('p.firstName :firstname')
            ->setParameter('firstname', $firstName)
            ->andWhere('p.lastName :lastname')
            ->setParameter('lastname', $lastName)
            ->getQuery();


        return $query->getFirstResult();
    }
}
