security_login:
    path:     /login
    defaults: { _controller: SecuritiesBundle:Security:login }

security_logout:
    path:     /logout
    defaults: { _controller: SecuritiesBundle:Security:logout }

user_register:
    path:     /register
    defaults: { _controller: SecuritiesBundle:Security:register }
